services:
  postgres-database:
    image: postgres:16.4-alpine
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: postgres-database

  payload:
    image: node:20-alpine
    container_name: payload
    depends_on:
      postgres-database:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
    labels:
      - 'traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000'
      - 'traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`${PROJECT_BASE_URL}`)'
    command: sh -c "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install && pnpm dev"

volumes:
  postgres-data:
    name: postgres-data
